const team = [
  {
    name: "Nihar Vankudre",
    position: "President",
    imgurl: "nihar.png",
    instagram: "https://instagram.com/this.is.nihar?igshid=NTA5ZTk1NTc=",
    linkedin: "https://www.linkedin.com/in/nihar-vankudre-777a3a206",
    phone: "+91 8452029034",
  },
  {
    name: "Aditya Mishra",
    imgurl: "adityamishra.png",
    position: "Vice President",
    instagram: "",
    linkedin: "https://www.linkedin.com/mwlite/in/aditya-mishra-b3081a20a",
    phone: "+91 6389614492",
  },
  {
    name: "Pranav Unkal",
    position: "Head Of Content Creation",
    imgurl: "pranav.jpeg",
    instagram: "https://www.instagram.com/pranav_5612/",
    linkedin: "https://www.linkedin.com/in/pranav-unkal",
    phone: "+91 9373829927",
  },
  // {
  //   name: "Aashish Mishra",
  //   position: "Treasurer",
  //   instagram: "http://instagram.com",
  //   linkedin: "http://linkedin.com",
  // },
  {
    name: "Om Dalavi",
    position: "Head Of Technology",
    imgurl: "om2.png",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/om-dalavi-7833a51b5/",
    phone: "+91 9654703319",
  },
  {
    name: "Bhushan Bahale",
    position: "Head Of Technology",
    imgurl: "bhushan.jpeg",
    instagram: "",
    linkedin: "",
    phone: "+91 9610657385",
  },
  {
    name: "Mayur Jadhav",
    position: "Head Of Public Relations",
    imgurl: "mayur.png",
    instagram: "https://www.instagram.com/mayur._9696/",
    linkedin: "https://www.linkedin.com/in/mayur-jadhav-56265720a",
    phone: "+91 9730200931",
  },
  {
    name: "Aditya Kakade",
    position: "Head Of Public Relations",
    imgurl: "adityak.png",
    instagram: "https://instagram.com/adikakade_20?igshid=NTA5ZTk1NTc=",
    linkedin: "https://www.linkedin.com/in/aditya-kakade-783109232",
    phone: "+91 7028420121",
  },
  {
    name: "Dhawal Diyewar",
    position: "Head Of Research",
    imgurl: "dhawal.png",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/dhawal-diyewar-32713824a",
    phone: "+91 9146462230",
  },

  // {
  //   name: "Swarali Kulkarni",
  //   position: "Head Of Content Creation",
  //   instagram: "http://instagram.com",
  //   linkedin: "http://linkedin.com",
  // },
  // {
  //   name: "Alisha Hatalkar",
  //   position: "Head Of Multimedia And Design",
  //   instagram: "http://instagram.com",
  //   linkedin: "http://linkedin.com",
  // },
  {
    name: "Vedashri Patil",
    position: "Head Of Research",
    imgurl: "vedashri.png",
    instagram: "",
    linkedin: "",
    phone: "+91 7350873585",
  },
];

export default team;
